### PR TITLE
docs: Add documentation

### PR DESCRIPTION
**Pull request by B1ue-Dev**
Title.

### CODE REVIEW

**Comment by B1ue-Dev** [comment]
Self-approved.

**Comment by sillyElv** [comment]
why did you delete the license?

**Comment by B1ue-Dev** [comment]
> why did you delete the license?

Wait, I did?

**Comment by sillyElv** [comment]
> > why did you delete the license?
> 
> Wait, I did?

grafik

**Comment by B1ue-Dev** [comment]
> > > why did you delete the license?
> > 
> > 
> > Wait, I did?
> 
> grafik

I have no idea with that then. I just moved to MIT and it still shows up in the branch though.
image

**Comment by sillyElv** [comment]
oh ok

**Pull request merged**
